### ISSUE TITLE
Code review summary #1

### ISSUE THREAD

**Issue by simplewepro** [NikSergeevi4/GlobalOpt#1]
### Tasks
- [x] add [prettier](https://www.npmjs.com/package/prettier) to autofix indentaions

### General
- [x] no need for separate forlder for 1 iamge

### HTML
https://github.com/NikSergeevi4/GlobalOpt/blob/1596bd5ce6a4fd1d6c9bd40d3b776d6ff7c5c441/src/index.html#L22 
- [x] `vertical_dot` class is unused
- [x] header phone number add margin or gap to prevent collapsing at low resolutions
- [x] refactor titles and subtitles to all be a `header` tags
- [x] hero banner lines refactor from fixed width to dynamic (% or flex)
- [x] adapt site for at least 1920px screens
- [x] consultattion section: rework logo and button to be centered at all screens
- [x] advantages section: add padding bottom to prevent text be at least bottom of section at lower res screens
https://github.com/NikSergeevi4/GlobalOpt/blob/1596bd5ce6a4fd1d6c9bd40d3b776d6ff7c5c441/src/index.html#L219
- [x] remove redundant whitespaces at the end of text blocks (may be auto fixed ny prettier)
https://github.com/NikSergeevi4/GlobalOpt/blob/1596bd5ce6a4fd1d6c9bd40d3b776d6ff7c5c441/src/index.html#L240
- [x] refactor from `div`s with `br` and `span` to multiple `p` tags
  - [x] also use more `p` for divs that contain text and semantic tags overall

### CSS
- [ ] move all colors to variables
- [x] refactor container from fixed padding to `max-width:1280px; margin: auto;`
- [x] refactor reusable classes to `_global.scss`
- [x] refactor footer:
  - [x] fix classes to proper scss nesting (add `.footer` instead of just tag selector)
  - [x] refactor red link to be BEM modifier instead of `nth-child`, refactor to `footer__link` element inside `footer` block
https://github.com/NikSergeevi4/GlobalOpt/blob/1596bd5ce6a4fd1d6c9bd40d3b776d6ff7c5c441/src/sass/blocks/_header.scss#L15
- [x] think about proper BEM classnames and nesting, `-item` is not seems to be valid modifier
- [x] header:
  - [x] last child in menu item refactor to `&:last-child`
- [x] add `text-wrap: balanced` to places where it does text more readable
